# Setup
title: Yu
tagline: null
url: https://yuuu14.github.io
paginate: 1
baseurl: "/blog"
permalink: pretty
related_posts: ""

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: compressed

# Markdown style, use MathJax support
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # inline instead of block
    block: false
    # use span instead of div
    span: true
    css-class: "highlight"
    inline_theme: "github"
  

  # syntax_highlighter: coderay
  # coderay-linenums-mode: inline
  # syntax_highlighter_opts:
  #   line_numbers:
  #   coderay_css: class

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: yuuu14
  url: https://yuuu14.github.io
  email: yu.xiao.14@outlook.com

# Custom vars
version: 3.0.0

# Custom navigation bar
bar:
  About: '/about'
  Archive: '/archive'
